/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Composent;
import java.awt.Point;
import javax.swing.SwingUtilities;


/**
 *
 * @author Julie Mignotte
 */
public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initJetons();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Plateau = new javax.swing.JLayeredPane();
        jeton1 = new Composent.Jeton();
        jeton2 = new Composent.Jeton();
        Cases = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Plateau.setBackground(new java.awt.Color(153, 255, 153));
        Plateau.setOpaque(true);

        jeton1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jeton1MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jeton1Layout = new javax.swing.GroupLayout(jeton1);
        jeton1.setLayout(jeton1Layout);
        jeton1Layout.setHorizontalGroup(
            jeton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jeton1Layout.setVerticalGroup(
            jeton1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Plateau.add(jeton1);
        jeton1.setBounds(160, 30, 50, 50);

        jeton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jeton2MouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jeton2Layout = new javax.swing.GroupLayout(jeton2);
        jeton2.setLayout(jeton2Layout);
        jeton2Layout.setHorizontalGroup(
            jeton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        jeton2Layout.setVerticalGroup(
            jeton2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        Plateau.add(jeton2);
        jeton2.setBounds(50, 50, 50, 50);

        javax.swing.GroupLayout CasesLayout = new javax.swing.GroupLayout(Cases);
        Cases.setLayout(CasesLayout);
        CasesLayout.setHorizontalGroup(
            CasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 360, Short.MAX_VALUE)
        );
        CasesLayout.setVerticalGroup(
            CasesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 290, Short.MAX_VALUE)
        );

        Plateau.add(Cases);
        Cases.setBounds(0, 0, 360, 290);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Plateau, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Plateau, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jeton1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeton1MouseDragged
        moveJeton(jeton1, evt.getPoint());
    }//GEN-LAST:event_jeton1MouseDragged

    private void jeton2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jeton2MouseDragged
        moveJeton(jeton2, evt.getPoint());
    }//GEN-LAST:event_jeton2MouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    private void initJetons(){
        jeton1.setImage("/Images/craneBleu.png");
        jeton2.setImage("/Images/craneRouge.png");
    }
    
    private void moveJeton(Jeton jeton, Point p){
        Point pos = SwingUtilities.convertPoint(jeton, p, Plateau);
        pos.setLocation(pos.getX() - (jeton.getWidth()/2), pos.getY() - (jeton.getHeight()/2));
        jeton.setLocation(pos);
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cases;
    private javax.swing.JLayeredPane Plateau;
    private Composent.Jeton jeton1;
    private Composent.Jeton jeton2;
    // End of variables declaration//GEN-END:variables
}
