/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package projetpirate;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import javax.imageio.ImageIO;

/**
 *
 * @author isaac
 */
public class imageJoueurCourant extends javax.swing.JPanel {
    private Image image;
    ArrayList<String> imJoueurs = new ArrayList<>(); 
    int joueurCourant = 0;
    
    
    /**
     * Creates new form imageJoueurCourant
     */
    public imageJoueurCourant() {
         try {
            // Charger l'image originale
            image = ImageIO.read(new File("../ProjetPirate/src/main/resources/women_pirate.jpg"));
         }catch(IOException e){
             e.printStackTrace();
         }
         imJoueurs.add("../ProjetPirate/src/main/resources/women_pirate.jpg");
         imJoueurs.add("../ProjetPirate/src/main/resources/case.png");
         
         
        initComponents();
    }
    
     
    @Override
    protected void paintComponent(Graphics g){
        super.paintComponent(g);
        Graphics2D g2 = (Graphics2D) g;

    int width = getWidth();
    int height = getHeight();

    // Dessine les parties de l'image
    g2.drawImage(image, 0,0, width, height, null);
    
    }
    
    public void nextJoueur() throws IOException{
        joueurCourant = (joueurCourant+1)%2;
        setImage(imJoueurs.get(joueurCourant));
        
    }
    
    public void setImage(String path) throws IOException{
        try {
            // Charger l'image originale
            image = ImageIO.read(new File(path));

        } catch (IOException e) {
            e.printStackTrace();
            // Gérer l'erreur ou fournir une image de secours
        }
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
