/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package src;

import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.Random;
import javax.imageio.ImageIO;
import javax.swing.Timer;

/**
 *
 * @author GBL4455A
 */
public class AffichageDes extends javax.swing.JPanel {

    /**
     * Creates new form Des
     */
    BufferedImage[] images = new BufferedImage[6];
    BufferedImage imageAAfficherD1;
    BufferedImage imageAAfficherD2;
    Timer timer;
    int compteur = 0;
    int limite = 20;
    int currentIndex = 0;
    int nbAAfficherD1 = 0;
    int nbAAfficherD2 = 0;
    public AffichageDes() {
        initComponents();
        try {
            for (int i = 0; i < 6; i++) {
                String n = i+1 + "";
                String path = getClass().getResource("/"+n +".PNG").getPath();
                
                images[i] = ImageIO.read(new File(path));

                timer = new Timer(50, (ActionEvent e) -> {
                    imageAAfficherD1 = images[new Random().nextInt(6)];
                    imageAAfficherD2 = images[new Random().nextInt(6)];
                    repaint();
                    compteur++;
                    if(compteur > limite){
                        timer.stop();
                        imageAAfficherD1 = images[nbAAfficherD1];
                        imageAAfficherD2 = images[nbAAfficherD2];
                        repaint();
                    }
                    
                });
            }
        } catch (IOException ex) {
            System.out.println("Erreur du chargement de l'image");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        jButton1.setText("jButton1");
        jButton1.setAlignmentY(0.0F);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jButton1)
                .addContainerGap(174, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(240, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(38, 38, 38))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Afficher(5, 2);
    }//GEN-LAST:event_jButton1MouseClicked
  
    void Afficher(int nbD1, int nbD2){
        compteur = 0;
        nbAAfficherD1 = nbD1-1;
        nbAAfficherD2 = nbD2-1;
        timer.start();
    }    
    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        
        if (imageAAfficherD1 != null && imageAAfficherD2 != null) {
            g.drawImage(imageAAfficherD1, 0, 0, this);
            g.drawImage(imageAAfficherD2, 150, 0, this);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
